import Descriptions from "@/components/Descriptions";
import Parent from "@/components/Parent";
import User from "@/components/User";
import Welcome from "@/components/Welcome";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Fundamentos do React</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Chamas!</h1>
        {/* Importando o componente */}
        <Welcome />
        <User />
        <Parent />

        {/* Chamando o componente e passando props */}
        <Descriptions name="Gusta" age={18}/>

        {/* Usando desestrururação para passar props */}
        <Dog name="Rex" breed="Salsicha"/>
      </main>
        
    </>
  );
}
